# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-13 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartEnergyMeter', '0002_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Energy',
        ),
        migrations.AddField(
            model_name='code',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 17, 52, 14, 294961)),
        ),
    ]
