# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartEnergyMeter', '0003_auto_20200113_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('house_number', models.TextField()),
                ('reading', models.FloatField()),
                ('payment', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
