# Generated by Django 3.0.2 on 2020-01-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartEnergyMeter', '0004_auto_20200129_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energymeter',
            options={'ordering': ('payment',), 'verbose_name_plural': 'EnergyMeter'},
        ),
    ]
